### PR TITLE
Switching to JSDoc syntax

### PR DESCRIPTION
**Pull request by azerpas**
Switching to JSDoc could help maintaining the documentation in a more readable way.
https://jsdoc.app/about-getting-started.html

### OLD
```js
/*
   Date.now()
*/
get_cf_date: function() {
   return Date.now ? Date.now() : +new Date();
}
```

### NEW
```js
/**
  * Returns the Date in a Unix time format https://en.wikipedia.org/wiki/Unix_time
  * @returns {number} Unix time (timestamp), e.g: 1631080958
*/
get_cf_date: function() {
   return Date.now ? Date.now() : +new Date();
}
```

### CODE REVIEW

**Comment by voidstar0** [comment]
Love this addition.

**Comment by azerpas** [comment]
The ternary operator in this line https://github.com/char/bpre/blob/ff4f024cd2808b0e35afcdf9793ba56abe85260f/akamai/1.7.js#L5 is preventing the activation of VS Code preview function.     

### With the ternary operator
with

### Without it
without

By removing the *if then* and just keeping the *else*, we could access the preview functionnality in the whole file.       
@char what do you think? I could add a comment like you did here: https://github.com/char/bpre/blob/ff4f024cd2808b0e35afcdf9793ba56abe85260f/akamai/1.7.js#L247-L252

**Comment by azerpas** [comment]
I've created an issue for it https://github.com/char/bpre/issues/10

**Comment by haze** [comment]
感谢您的工作!

**Comment by azerpas** [comment]
Ended the conversion. There's still a few properties that need to be defined, but I guess it can be done outside of this PR. Ready to merge @char 🙂

**Comment by voidstar0** [comment]
LGTM!

**Pull request merged**
